package com.example.githubclient.bot;

public enum BotState {
    START,
    FILLING_NEW_STUDENT_DATA,
    ASK_FIRST_NAME,
    ASK_LAST_NAME,
    ASK_GITHUB_LOGIN,
    FILLED_STUDENT_ADDITION,
    SHOW_MAIN_MENU,
    SHOW_STUDENTS_LIST,
    SHOW_REPOS_LIST,
    CHECK_EXACT_REPO,
    ASK_CHECK_REPO_NAME,
    ASK_OWNER_LOGIN,
    CHECKED_EXACT_REPO,
    CHECK_ALL_REPOS
}
